# Welcome to Jekyll!

# Site settings
# These are used to personalize your new site.
# GitHub Pages-compatible theme setup
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"

skin: "/assets/css/skins/default.css"
locale: en-US
title: "sageev oore blog"
description: "will be posting stuff here"
baseurl: "" # leave blank unless you're using a subpath like "/blog"
url: "https://osageev.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200

mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.
  tags:  # "none", "ams" (default), "all"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics: # Google Analytics id
disqus:
  shortname: # Disqus shortname

twitter:
  username: # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown

feed:
  path: atom.xml

# Pagination
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Plugins (GitHub Pages-approved)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# trigger rebuild
